# Generated by Django 5.2 on 2025-06-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(
                    help_text='Title of the task',
                    max_length=255
                )),
                ('description', models.TextField(
                    blank=True,
                    help_text='Optional description of the task',
                    null=True
                )),
                ('is_completed', models.BooleanField(
                    default=False,
                    help_text='Task completion status'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Timestamp when the task was created'
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    help_text='Timestamp when the task was last updated'
                )),
            ],
        ),
    ]
